services:
  - type: web
    name: credit-risk-assessment-system
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
